[package]
name = "inbound_call"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
elevenlabs_twilio = { path = "../../integrations/twilio" }
axum = { version = "0.8.1", features = ["ws"] }
tokio = "1.42.0"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
