[package]
name = "ttd_rig_gemini"
version = "0.1.0"
edition = "2024"

[dependencies]
elevenlabs_rs = { path = "../../elevenlabs_rs"}
rig-core = "0.18.2"
serde_json = "1.0.143"
tokio = "1.47.1"
serde = { version = "1.0.219", features = ["derive"] }
